// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewAddUserToWorkspaceParams creates a new AddUserToWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddUserToWorkspaceParams() *AddUserToWorkspaceParams {
	return &AddUserToWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddUserToWorkspaceParamsWithTimeout creates a new AddUserToWorkspaceParams object
// with the ability to set a timeout on a request.
func NewAddUserToWorkspaceParamsWithTimeout(timeout time.Duration) *AddUserToWorkspaceParams {
	return &AddUserToWorkspaceParams{
		timeout: timeout,
	}
}

// NewAddUserToWorkspaceParamsWithContext creates a new AddUserToWorkspaceParams object
// with the ability to set a context for a request.
func NewAddUserToWorkspaceParamsWithContext(ctx context.Context) *AddUserToWorkspaceParams {
	return &AddUserToWorkspaceParams{
		Context: ctx,
	}
}

// NewAddUserToWorkspaceParamsWithHTTPClient creates a new AddUserToWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddUserToWorkspaceParamsWithHTTPClient(client *http.Client) *AddUserToWorkspaceParams {
	return &AddUserToWorkspaceParams{
		HTTPClient: client,
	}
}

/*
AddUserToWorkspaceParams contains all the parameters to send to the API endpoint

	for the add user to workspace operation.

	Typically these are written to a http.Request.
*/
type AddUserToWorkspaceParams struct {

	/* Payload.

	   AddUserToWorkspaceBody
	*/
	Payload *models.AddUserToWorkspaceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add user to workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUserToWorkspaceParams) WithDefaults() *AddUserToWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add user to workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddUserToWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add user to workspace params
func (o *AddUserToWorkspaceParams) WithTimeout(timeout time.Duration) *AddUserToWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add user to workspace params
func (o *AddUserToWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add user to workspace params
func (o *AddUserToWorkspaceParams) WithContext(ctx context.Context) *AddUserToWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add user to workspace params
func (o *AddUserToWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add user to workspace params
func (o *AddUserToWorkspaceParams) WithHTTPClient(client *http.Client) *AddUserToWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add user to workspace params
func (o *AddUserToWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the add user to workspace params
func (o *AddUserToWorkspaceParams) WithPayload(payload *models.AddUserToWorkspaceBody) *AddUserToWorkspaceParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the add user to workspace params
func (o *AddUserToWorkspaceParams) SetPayload(payload *models.AddUserToWorkspaceBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *AddUserToWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
