// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// CreateWorkspaceReader is a Reader for the CreateWorkspace structure.
type CreateWorkspaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWorkspaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateWorkspaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateWorkspaceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateWorkspaceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /workspace.createWorkspace] createWorkspace", response, response.Code())
	}
}

// NewCreateWorkspaceOK creates a CreateWorkspaceOK with default headers values
func NewCreateWorkspaceOK() *CreateWorkspaceOK {
	return &CreateWorkspaceOK{}
}

/*
CreateWorkspaceOK describes a response with status code 200, with default header values.

OK
*/
type CreateWorkspaceOK struct {
	Payload *models.HandlersResponseString
}

// IsSuccess returns true when this create workspace o k response has a 2xx status code
func (o *CreateWorkspaceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create workspace o k response has a 3xx status code
func (o *CreateWorkspaceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workspace o k response has a 4xx status code
func (o *CreateWorkspaceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workspace o k response has a 5xx status code
func (o *CreateWorkspaceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create workspace o k response a status code equal to that given
func (o *CreateWorkspaceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create workspace o k response
func (o *CreateWorkspaceOK) Code() int {
	return 200
}

func (o *CreateWorkspaceOK) Error() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceOK  %+v", 200, o.Payload)
}

func (o *CreateWorkspaceOK) String() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceOK  %+v", 200, o.Payload)
}

func (o *CreateWorkspaceOK) GetPayload() *models.HandlersResponseString {
	return o.Payload
}

func (o *CreateWorkspaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersResponseString)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkspaceBadRequest creates a CreateWorkspaceBadRequest with default headers values
func NewCreateWorkspaceBadRequest() *CreateWorkspaceBadRequest {
	return &CreateWorkspaceBadRequest{}
}

/*
CreateWorkspaceBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateWorkspaceBadRequest struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this create workspace bad request response has a 2xx status code
func (o *CreateWorkspaceBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workspace bad request response has a 3xx status code
func (o *CreateWorkspaceBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workspace bad request response has a 4xx status code
func (o *CreateWorkspaceBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create workspace bad request response has a 5xx status code
func (o *CreateWorkspaceBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create workspace bad request response a status code equal to that given
func (o *CreateWorkspaceBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create workspace bad request response
func (o *CreateWorkspaceBadRequest) Code() int {
	return 400
}

func (o *CreateWorkspaceBadRequest) Error() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceBadRequest  %+v", 400, o.Payload)
}

func (o *CreateWorkspaceBadRequest) String() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceBadRequest  %+v", 400, o.Payload)
}

func (o *CreateWorkspaceBadRequest) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *CreateWorkspaceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWorkspaceInternalServerError creates a CreateWorkspaceInternalServerError with default headers values
func NewCreateWorkspaceInternalServerError() *CreateWorkspaceInternalServerError {
	return &CreateWorkspaceInternalServerError{}
}

/*
CreateWorkspaceInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateWorkspaceInternalServerError struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this create workspace internal server error response has a 2xx status code
func (o *CreateWorkspaceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create workspace internal server error response has a 3xx status code
func (o *CreateWorkspaceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create workspace internal server error response has a 4xx status code
func (o *CreateWorkspaceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create workspace internal server error response has a 5xx status code
func (o *CreateWorkspaceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create workspace internal server error response a status code equal to that given
func (o *CreateWorkspaceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create workspace internal server error response
func (o *CreateWorkspaceInternalServerError) Code() int {
	return 500
}

func (o *CreateWorkspaceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateWorkspaceInternalServerError) String() string {
	return fmt.Sprintf("[POST /workspace.createWorkspace][%d] createWorkspaceInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateWorkspaceInternalServerError) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *CreateWorkspaceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
