// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// FindAllWorkspacesReader is a Reader for the FindAllWorkspaces structure.
type FindAllWorkspacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindAllWorkspacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindAllWorkspacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewFindAllWorkspacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewFindAllWorkspacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /workspace.findAllWorkspaces] findAllWorkspaces", response, response.Code())
	}
}

// NewFindAllWorkspacesOK creates a FindAllWorkspacesOK with default headers values
func NewFindAllWorkspacesOK() *FindAllWorkspacesOK {
	return &FindAllWorkspacesOK{}
}

/*
FindAllWorkspacesOK describes a response with status code 200, with default header values.

OK
*/
type FindAllWorkspacesOK struct {
	Payload *models.HandlersResponseArrayFindAllWorkspacesResponse
}

// IsSuccess returns true when this find all workspaces o k response has a 2xx status code
func (o *FindAllWorkspacesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this find all workspaces o k response has a 3xx status code
func (o *FindAllWorkspacesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find all workspaces o k response has a 4xx status code
func (o *FindAllWorkspacesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this find all workspaces o k response has a 5xx status code
func (o *FindAllWorkspacesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this find all workspaces o k response a status code equal to that given
func (o *FindAllWorkspacesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the find all workspaces o k response
func (o *FindAllWorkspacesOK) Code() int {
	return 200
}

func (o *FindAllWorkspacesOK) Error() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesOK  %+v", 200, o.Payload)
}

func (o *FindAllWorkspacesOK) String() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesOK  %+v", 200, o.Payload)
}

func (o *FindAllWorkspacesOK) GetPayload() *models.HandlersResponseArrayFindAllWorkspacesResponse {
	return o.Payload
}

func (o *FindAllWorkspacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersResponseArrayFindAllWorkspacesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindAllWorkspacesBadRequest creates a FindAllWorkspacesBadRequest with default headers values
func NewFindAllWorkspacesBadRequest() *FindAllWorkspacesBadRequest {
	return &FindAllWorkspacesBadRequest{}
}

/*
FindAllWorkspacesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type FindAllWorkspacesBadRequest struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this find all workspaces bad request response has a 2xx status code
func (o *FindAllWorkspacesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this find all workspaces bad request response has a 3xx status code
func (o *FindAllWorkspacesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find all workspaces bad request response has a 4xx status code
func (o *FindAllWorkspacesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this find all workspaces bad request response has a 5xx status code
func (o *FindAllWorkspacesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this find all workspaces bad request response a status code equal to that given
func (o *FindAllWorkspacesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the find all workspaces bad request response
func (o *FindAllWorkspacesBadRequest) Code() int {
	return 400
}

func (o *FindAllWorkspacesBadRequest) Error() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesBadRequest  %+v", 400, o.Payload)
}

func (o *FindAllWorkspacesBadRequest) String() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesBadRequest  %+v", 400, o.Payload)
}

func (o *FindAllWorkspacesBadRequest) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *FindAllWorkspacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindAllWorkspacesInternalServerError creates a FindAllWorkspacesInternalServerError with default headers values
func NewFindAllWorkspacesInternalServerError() *FindAllWorkspacesInternalServerError {
	return &FindAllWorkspacesInternalServerError{}
}

/*
FindAllWorkspacesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type FindAllWorkspacesInternalServerError struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this find all workspaces internal server error response has a 2xx status code
func (o *FindAllWorkspacesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this find all workspaces internal server error response has a 3xx status code
func (o *FindAllWorkspacesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this find all workspaces internal server error response has a 4xx status code
func (o *FindAllWorkspacesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this find all workspaces internal server error response has a 5xx status code
func (o *FindAllWorkspacesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this find all workspaces internal server error response a status code equal to that given
func (o *FindAllWorkspacesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the find all workspaces internal server error response
func (o *FindAllWorkspacesInternalServerError) Code() int {
	return 500
}

func (o *FindAllWorkspacesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesInternalServerError  %+v", 500, o.Payload)
}

func (o *FindAllWorkspacesInternalServerError) String() string {
	return fmt.Sprintf("[POST /workspace.findAllWorkspaces][%d] findAllWorkspacesInternalServerError  %+v", 500, o.Payload)
}

func (o *FindAllWorkspacesInternalServerError) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *FindAllWorkspacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
