// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewFindAllWorkspacesParams creates a new FindAllWorkspacesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindAllWorkspacesParams() *FindAllWorkspacesParams {
	return &FindAllWorkspacesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindAllWorkspacesParamsWithTimeout creates a new FindAllWorkspacesParams object
// with the ability to set a timeout on a request.
func NewFindAllWorkspacesParamsWithTimeout(timeout time.Duration) *FindAllWorkspacesParams {
	return &FindAllWorkspacesParams{
		timeout: timeout,
	}
}

// NewFindAllWorkspacesParamsWithContext creates a new FindAllWorkspacesParams object
// with the ability to set a context for a request.
func NewFindAllWorkspacesParamsWithContext(ctx context.Context) *FindAllWorkspacesParams {
	return &FindAllWorkspacesParams{
		Context: ctx,
	}
}

// NewFindAllWorkspacesParamsWithHTTPClient creates a new FindAllWorkspacesParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindAllWorkspacesParamsWithHTTPClient(client *http.Client) *FindAllWorkspacesParams {
	return &FindAllWorkspacesParams{
		HTTPClient: client,
	}
}

/*
FindAllWorkspacesParams contains all the parameters to send to the API endpoint

	for the find all workspaces operation.

	Typically these are written to a http.Request.
*/
type FindAllWorkspacesParams struct {

	/* Payload.

	   FindAllWorkspacesBody
	*/
	Payload *models.FindAllWorkspacesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find all workspaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllWorkspacesParams) WithDefaults() *FindAllWorkspacesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find all workspaces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllWorkspacesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find all workspaces params
func (o *FindAllWorkspacesParams) WithTimeout(timeout time.Duration) *FindAllWorkspacesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find all workspaces params
func (o *FindAllWorkspacesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find all workspaces params
func (o *FindAllWorkspacesParams) WithContext(ctx context.Context) *FindAllWorkspacesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find all workspaces params
func (o *FindAllWorkspacesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find all workspaces params
func (o *FindAllWorkspacesParams) WithHTTPClient(client *http.Client) *FindAllWorkspacesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find all workspaces params
func (o *FindAllWorkspacesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the find all workspaces params
func (o *FindAllWorkspacesParams) WithPayload(payload *models.FindAllWorkspacesBody) *FindAllWorkspacesParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the find all workspaces params
func (o *FindAllWorkspacesParams) SetPayload(payload *models.FindAllWorkspacesBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *FindAllWorkspacesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
