// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewRemoveUserFromWorkspaceParams creates a new RemoveUserFromWorkspaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveUserFromWorkspaceParams() *RemoveUserFromWorkspaceParams {
	return &RemoveUserFromWorkspaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveUserFromWorkspaceParamsWithTimeout creates a new RemoveUserFromWorkspaceParams object
// with the ability to set a timeout on a request.
func NewRemoveUserFromWorkspaceParamsWithTimeout(timeout time.Duration) *RemoveUserFromWorkspaceParams {
	return &RemoveUserFromWorkspaceParams{
		timeout: timeout,
	}
}

// NewRemoveUserFromWorkspaceParamsWithContext creates a new RemoveUserFromWorkspaceParams object
// with the ability to set a context for a request.
func NewRemoveUserFromWorkspaceParamsWithContext(ctx context.Context) *RemoveUserFromWorkspaceParams {
	return &RemoveUserFromWorkspaceParams{
		Context: ctx,
	}
}

// NewRemoveUserFromWorkspaceParamsWithHTTPClient creates a new RemoveUserFromWorkspaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveUserFromWorkspaceParamsWithHTTPClient(client *http.Client) *RemoveUserFromWorkspaceParams {
	return &RemoveUserFromWorkspaceParams{
		HTTPClient: client,
	}
}

/*
RemoveUserFromWorkspaceParams contains all the parameters to send to the API endpoint

	for the remove user from workspace operation.

	Typically these are written to a http.Request.
*/
type RemoveUserFromWorkspaceParams struct {

	/* Payload.

	   RemoveUserFromWorkspaceBody
	*/
	Payload *models.RemoveUserFromWorkspaceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove user from workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveUserFromWorkspaceParams) WithDefaults() *RemoveUserFromWorkspaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove user from workspace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveUserFromWorkspaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) WithTimeout(timeout time.Duration) *RemoveUserFromWorkspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) WithContext(ctx context.Context) *RemoveUserFromWorkspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) WithHTTPClient(client *http.Client) *RemoveUserFromWorkspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) WithPayload(payload *models.RemoveUserFromWorkspaceBody) *RemoveUserFromWorkspaceParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the remove user from workspace params
func (o *RemoveUserFromWorkspaceParams) SetPayload(payload *models.RemoveUserFromWorkspaceBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveUserFromWorkspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
