// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddUserToWorkspaceBody add user to workspace body
//
// swagger:model AddUserToWorkspaceBody
type AddUserToWorkspaceBody struct {

	// user id
	UserID string `json:"user_id,omitempty"`

	// workspace id
	WorkspaceID string `json:"workspace_id,omitempty"`
}

// Validate validates this add user to workspace body
func (m *AddUserToWorkspaceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add user to workspace body based on context it is used
func (m *AddUserToWorkspaceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddUserToWorkspaceBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddUserToWorkspaceBody) UnmarshalBinary(b []byte) error {
	var res AddUserToWorkspaceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
