// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteWorkspaceBody delete workspace body
//
// swagger:model DeleteWorkspaceBody
type DeleteWorkspaceBody struct {

	// workspace id
	WorkspaceID string `json:"workspace_id,omitempty"`
}

// Validate validates this delete workspace body
func (m *DeleteWorkspaceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete workspace body based on context it is used
func (m *DeleteWorkspaceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteWorkspaceBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteWorkspaceBody) UnmarshalBinary(b []byte) error {
	var res DeleteWorkspaceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
