// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HandlersResponseString handlers response string
//
// swagger:model handlers.Response-string
type HandlersResponseString struct {

	// code
	Code int64 `json:"code,omitempty"`

	// data
	Data string `json:"data,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// timestamp
	Timestamp string `json:"timestamp,omitempty"`
}

// Validate validates this handlers response string
func (m *HandlersResponseString) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this handlers response string based on context it is used
func (m *HandlersResponseString) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HandlersResponseString) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HandlersResponseString) UnmarshalBinary(b []byte) error {
	var res HandlersResponseString
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
