// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateSecretByIDBody update secret by Id body
//
// swagger:model UpdateSecretByIdBody
type UpdateSecretByIDBody struct {

	// secret id
	SecretID string `json:"secret_id,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this update secret by Id body
func (m *UpdateSecretByIDBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update secret by Id body based on context it is used
func (m *UpdateSecretByIDBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateSecretByIDBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateSecretByIDBody) UnmarshalBinary(b []byte) error {
	var res UpdateSecretByIDBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
