SERVER_ORIGINS: http://localhost:3000,http://localhost:8080,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:8080,http://127.0.0.1:5173
DB_NAME: postgres
DB_USERNAME: root
DB_HOST: localhost
SERVER_HOST: 0.0.0.0
DB_PASSWORD: password
JWT_SECRET: thisisthesecret
DB_PORT: 5432
DB_AUTOMIGRATE: true
SERVER_PORT: 8080
