// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// CreateSecretReader is a Reader for the CreateSecret structure.
type CreateSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /secret.createSecret] createSecret", response, response.Code())
	}
}

// NewCreateSecretOK creates a CreateSecretOK with default headers values
func NewCreateSecretOK() *CreateSecretOK {
	return &CreateSecretOK{}
}

/*
CreateSecretOK describes a response with status code 200, with default header values.

OK
*/
type CreateSecretOK struct {
	Payload *models.HandlersResponseString
}

// IsSuccess returns true when this create secret o k response has a 2xx status code
func (o *CreateSecretOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create secret o k response has a 3xx status code
func (o *CreateSecretOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create secret o k response has a 4xx status code
func (o *CreateSecretOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create secret o k response has a 5xx status code
func (o *CreateSecretOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create secret o k response a status code equal to that given
func (o *CreateSecretOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create secret o k response
func (o *CreateSecretOK) Code() int {
	return 200
}

func (o *CreateSecretOK) Error() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretOK  %+v", 200, o.Payload)
}

func (o *CreateSecretOK) String() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretOK  %+v", 200, o.Payload)
}

func (o *CreateSecretOK) GetPayload() *models.HandlersResponseString {
	return o.Payload
}

func (o *CreateSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersResponseString)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecretBadRequest creates a CreateSecretBadRequest with default headers values
func NewCreateSecretBadRequest() *CreateSecretBadRequest {
	return &CreateSecretBadRequest{}
}

/*
CreateSecretBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateSecretBadRequest struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this create secret bad request response has a 2xx status code
func (o *CreateSecretBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create secret bad request response has a 3xx status code
func (o *CreateSecretBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create secret bad request response has a 4xx status code
func (o *CreateSecretBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create secret bad request response has a 5xx status code
func (o *CreateSecretBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create secret bad request response a status code equal to that given
func (o *CreateSecretBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create secret bad request response
func (o *CreateSecretBadRequest) Code() int {
	return 400
}

func (o *CreateSecretBadRequest) Error() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSecretBadRequest) String() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSecretBadRequest) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *CreateSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecretInternalServerError creates a CreateSecretInternalServerError with default headers values
func NewCreateSecretInternalServerError() *CreateSecretInternalServerError {
	return &CreateSecretInternalServerError{}
}

/*
CreateSecretInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateSecretInternalServerError struct {
	Payload *models.HandlersErrResponse
}

// IsSuccess returns true when this create secret internal server error response has a 2xx status code
func (o *CreateSecretInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create secret internal server error response has a 3xx status code
func (o *CreateSecretInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create secret internal server error response has a 4xx status code
func (o *CreateSecretInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create secret internal server error response has a 5xx status code
func (o *CreateSecretInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create secret internal server error response a status code equal to that given
func (o *CreateSecretInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create secret internal server error response
func (o *CreateSecretInternalServerError) Code() int {
	return 500
}

func (o *CreateSecretInternalServerError) Error() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSecretInternalServerError) String() string {
	return fmt.Sprintf("[POST /secret.createSecret][%d] createSecretInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSecretInternalServerError) GetPayload() *models.HandlersErrResponse {
	return o.Payload
}

func (o *CreateSecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HandlersErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
