// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewDeleteSecretByIDParams creates a new DeleteSecretByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSecretByIDParams() *DeleteSecretByIDParams {
	return &DeleteSecretByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSecretByIDParamsWithTimeout creates a new DeleteSecretByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteSecretByIDParamsWithTimeout(timeout time.Duration) *DeleteSecretByIDParams {
	return &DeleteSecretByIDParams{
		timeout: timeout,
	}
}

// NewDeleteSecretByIDParamsWithContext creates a new DeleteSecretByIDParams object
// with the ability to set a context for a request.
func NewDeleteSecretByIDParamsWithContext(ctx context.Context) *DeleteSecretByIDParams {
	return &DeleteSecretByIDParams{
		Context: ctx,
	}
}

// NewDeleteSecretByIDParamsWithHTTPClient creates a new DeleteSecretByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSecretByIDParamsWithHTTPClient(client *http.Client) *DeleteSecretByIDParams {
	return &DeleteSecretByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteSecretByIDParams contains all the parameters to send to the API endpoint

	for the delete secret by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteSecretByIDParams struct {

	/* Payload.

	   DeleteSecretByIdBody
	*/
	Payload *models.DeleteSecretByIDBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete secret by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSecretByIDParams) WithDefaults() *DeleteSecretByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete secret by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSecretByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete secret by Id params
func (o *DeleteSecretByIDParams) WithTimeout(timeout time.Duration) *DeleteSecretByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete secret by Id params
func (o *DeleteSecretByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete secret by Id params
func (o *DeleteSecretByIDParams) WithContext(ctx context.Context) *DeleteSecretByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete secret by Id params
func (o *DeleteSecretByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete secret by Id params
func (o *DeleteSecretByIDParams) WithHTTPClient(client *http.Client) *DeleteSecretByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete secret by Id params
func (o *DeleteSecretByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the delete secret by Id params
func (o *DeleteSecretByIDParams) WithPayload(payload *models.DeleteSecretByIDBody) *DeleteSecretByIDParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the delete secret by Id params
func (o *DeleteSecretByIDParams) SetPayload(payload *models.DeleteSecretByIDBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSecretByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
