// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewFindSecretsByEnvModeParams creates a new FindSecretsByEnvModeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindSecretsByEnvModeParams() *FindSecretsByEnvModeParams {
	return &FindSecretsByEnvModeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindSecretsByEnvModeParamsWithTimeout creates a new FindSecretsByEnvModeParams object
// with the ability to set a timeout on a request.
func NewFindSecretsByEnvModeParamsWithTimeout(timeout time.Duration) *FindSecretsByEnvModeParams {
	return &FindSecretsByEnvModeParams{
		timeout: timeout,
	}
}

// NewFindSecretsByEnvModeParamsWithContext creates a new FindSecretsByEnvModeParams object
// with the ability to set a context for a request.
func NewFindSecretsByEnvModeParamsWithContext(ctx context.Context) *FindSecretsByEnvModeParams {
	return &FindSecretsByEnvModeParams{
		Context: ctx,
	}
}

// NewFindSecretsByEnvModeParamsWithHTTPClient creates a new FindSecretsByEnvModeParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindSecretsByEnvModeParamsWithHTTPClient(client *http.Client) *FindSecretsByEnvModeParams {
	return &FindSecretsByEnvModeParams{
		HTTPClient: client,
	}
}

/*
FindSecretsByEnvModeParams contains all the parameters to send to the API endpoint

	for the find secrets by env mode operation.

	Typically these are written to a http.Request.
*/
type FindSecretsByEnvModeParams struct {

	/* Payload.

	   FindSecretsByEnvModeBody
	*/
	Payload *models.FindSecretsByEnvModeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find secrets by env mode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindSecretsByEnvModeParams) WithDefaults() *FindSecretsByEnvModeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find secrets by env mode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindSecretsByEnvModeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) WithTimeout(timeout time.Duration) *FindSecretsByEnvModeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) WithContext(ctx context.Context) *FindSecretsByEnvModeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) WithHTTPClient(client *http.Client) *FindSecretsByEnvModeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) WithPayload(payload *models.FindSecretsByEnvModeBody) *FindSecretsByEnvModeParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the find secrets by env mode params
func (o *FindSecretsByEnvModeParams) SetPayload(payload *models.FindSecretsByEnvModeBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *FindSecretsByEnvModeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
