// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/wuhoops/silenda/cli/models"
)

// NewFindAllSecretsByWorkspaceIDParams creates a new FindAllSecretsByWorkspaceIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindAllSecretsByWorkspaceIDParams() *FindAllSecretsByWorkspaceIDParams {
	return &FindAllSecretsByWorkspaceIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindAllSecretsByWorkspaceIDParamsWithTimeout creates a new FindAllSecretsByWorkspaceIDParams object
// with the ability to set a timeout on a request.
func NewFindAllSecretsByWorkspaceIDParamsWithTimeout(timeout time.Duration) *FindAllSecretsByWorkspaceIDParams {
	return &FindAllSecretsByWorkspaceIDParams{
		timeout: timeout,
	}
}

// NewFindAllSecretsByWorkspaceIDParamsWithContext creates a new FindAllSecretsByWorkspaceIDParams object
// with the ability to set a context for a request.
func NewFindAllSecretsByWorkspaceIDParamsWithContext(ctx context.Context) *FindAllSecretsByWorkspaceIDParams {
	return &FindAllSecretsByWorkspaceIDParams{
		Context: ctx,
	}
}

// NewFindAllSecretsByWorkspaceIDParamsWithHTTPClient creates a new FindAllSecretsByWorkspaceIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindAllSecretsByWorkspaceIDParamsWithHTTPClient(client *http.Client) *FindAllSecretsByWorkspaceIDParams {
	return &FindAllSecretsByWorkspaceIDParams{
		HTTPClient: client,
	}
}

/*
FindAllSecretsByWorkspaceIDParams contains all the parameters to send to the API endpoint

	for the find all secrets by workspace Id operation.

	Typically these are written to a http.Request.
*/
type FindAllSecretsByWorkspaceIDParams struct {

	/* Payload.

	   FindAllSecretsByWorkspaceIdBody
	*/
	Payload *models.FindAllSecretsByWorkspaceIDBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find all secrets by workspace Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllSecretsByWorkspaceIDParams) WithDefaults() *FindAllSecretsByWorkspaceIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find all secrets by workspace Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllSecretsByWorkspaceIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) WithTimeout(timeout time.Duration) *FindAllSecretsByWorkspaceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) WithContext(ctx context.Context) *FindAllSecretsByWorkspaceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) WithHTTPClient(client *http.Client) *FindAllSecretsByWorkspaceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) WithPayload(payload *models.FindAllSecretsByWorkspaceIDBody) *FindAllSecretsByWorkspaceIDParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the find all secrets by workspace Id params
func (o *FindAllSecretsByWorkspaceIDParams) SetPayload(payload *models.FindAllSecretsByWorkspaceIDBody) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *FindAllSecretsByWorkspaceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
