// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new secret API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for secret API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	CreateSecret(params *CreateSecretParams, opts ...ClientOption) (*CreateSecretOK, error)

	DeleteSecretByID(params *DeleteSecretByIDParams, opts ...ClientOption) (*DeleteSecretByIDOK, error)

	FindSecretsByEnvMode(params *FindSecretsByEnvModeParams, opts ...ClientOption) (*FindSecretsByEnvModeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
CreateSecret creates secret
*/
func (a *Client) CreateSecret(params *CreateSecretParams, opts ...ClientOption) (*CreateSecretOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateSecretParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "createSecret",
		Method:             "POST",
		PathPattern:        "/secret.createSecret",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateSecretReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateSecretOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createSecret: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
DeleteSecretByID deletes secret by id
*/
func (a *Client) DeleteSecretByID(params *DeleteSecretByIDParams, opts ...ClientOption) (*DeleteSecretByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteSecretByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteSecretById",
		Method:             "POST",
		PathPattern:        "/secret.deleteSecretByID",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteSecretByIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteSecretByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteSecretById: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
FindSecretsByEnvMode finds secrets by env mode
*/
func (a *Client) FindSecretsByEnvMode(params *FindSecretsByEnvModeParams, opts ...ClientOption) (*FindSecretsByEnvModeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewFindSecretsByEnvModeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "findSecretsByEnvMode",
		Method:             "POST",
		PathPattern:        "/secret.findSecretsByEnvMode",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &FindSecretsByEnvModeReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*FindSecretsByEnvModeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for findSecretsByEnvMode: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
