definitions:
  AddUserToWorkspaceBody:
    properties:
      user_id:
        type: string
      workspace_id:
        type: string
    type: object
  CreateSecretBody:
    properties:
      env_mode:
        type: string
      key:
        type: string
      value:
        type: string
      workspace_id:
        type: string
    type: object
  CreateWorkspaceBody:
    properties:
      name:
        type: string
      owner:
        type: string
    type: object
  DeleteSecretByIdBody:
    properties:
      secret_id:
        type: string
    type: object
  DeleteWorkspaceBody:
    properties:
      workspace_id:
        type: string
    type: object
  FindAllSecretsByWorkspaceIdBody:
    properties:
      workspace_id:
        type: string
    type: object
  FindAllSecretsByWorkspaceIdResponse:
    properties:
      dev:
        items:
          $ref: '#/definitions/FindSecretsByEnvModeResponse'
        type: array
      prod:
        items:
          $ref: '#/definitions/FindSecretsByEnvModeResponse'
        type: array
      stage:
        items:
          $ref: '#/definitions/FindSecretsByEnvModeResponse'
        type: array
    type: object
  FindAllWorkspacesBody:
    properties:
      owner:
        type: string
    type: object
  FindAllWorkspacesResponse:
    properties:
      id:
        type: string
      name:
        type: string
      owner:
        type: string
    type: object
  FindSecretsByEnvModeBody:
    properties:
      env_mode:
        type: string
      workspace_id:
        type: string
    type: object
  FindSecretsByEnvModeResponse:
    properties:
      id:
        type: string
      key:
        type: string
      value:
        type: string
    type: object
  RemoveUserFromWorkspaceBody:
    properties:
      user_id:
        type: string
      workspace_id:
        type: string
    type: object
  UpdateSecretByIdBody:
    properties:
      secret_id:
        type: string
      value:
        type: string
    type: object
  UpdateWorkspaceBody:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  handlers.ErrResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-array_FindAllWorkspacesResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/FindAllWorkspacesResponse'
        type: array
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-array_FindSecretsByEnvModeResponse:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/FindSecretsByEnvModeResponse'
        type: array
      message:
        type: string
      timestamp:
        type: string
    type: object
  handlers.Response-string:
    properties:
      code:
        type: integer
      data:
        type: string
      message:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact:
    email: pasinun.w@gmail.com
    name: Pasinun.w
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Silenda API
  version: "1.0"
paths:
  /secret.createSecret:
    post:
      consumes:
      - application/json
      operationId: createSecret
      parameters:
      - description: CreateSecretBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateSecretBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Create secret
      tags:
      - secret
  /secret.deleteSecretByID:
    post:
      consumes:
      - application/json
      operationId: deleteSecretById
      parameters:
      - description: DeleteSecretByIdBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DeleteSecretByIdBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete secret by id
      tags:
      - secret
  /secret.findAllSecretsByWorkspaceId:
    post:
      consumes:
      - application/json
      operationId: findAllSecretsByWorkspaceId
      parameters:
      - description: FindAllSecretsByWorkspaceIdBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/FindAllSecretsByWorkspaceIdBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/FindAllSecretsByWorkspaceIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Find all secrets by workspace id
      tags:
      - secret
  /secret.findSecretsByEnvMode:
    post:
      consumes:
      - application/json
      operationId: findSecretsByEnvMode
      parameters:
      - description: FindSecretsByEnvModeBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/FindSecretsByEnvModeBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-array_FindSecretsByEnvModeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Find secrets by env mode
      tags:
      - secret
  /secret.updateSecret:
    post:
      consumes:
      - application/json
      operationId: updateSecret
      parameters:
      - description: UpdateSecretByIdBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateSecretByIdBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Update secret
      tags:
      - secret
  /workspace.addUserToWorkspace:
    post:
      consumes:
      - application/json
      operationId: addUserToWorkspace
      parameters:
      - description: AddUserToWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/AddUserToWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Add user to workspace
      tags:
      - workspace
  /workspace.createWorkspace:
    post:
      consumes:
      - application/json
      operationId: createWorkspace
      parameters:
      - description: CreateWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Create a new workspace
      tags:
      - workspace
  /workspace.deleteWorkspace/{id}:
    delete:
      consumes:
      - application/json
      operationId: deleteWorkspace
      parameters:
      - description: DeleteWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DeleteWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Delete workspace
      tags:
      - workspace
  /workspace.findAllWorkspaces:
    post:
      consumes:
      - application/json
      operationId: findAllWorkspaces
      parameters:
      - description: FindAllWorkspacesBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/FindAllWorkspacesBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-array_FindAllWorkspacesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Find all workspaces
      tags:
      - workspace
  /workspace.removeUserFromWorkspace:
    delete:
      consumes:
      - application/json
      operationId: removeUserFromWorkspace
      parameters:
      - description: RemoveUserFromWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RemoveUserFromWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Remove user from workspace
      tags:
      - workspace
  /workspace.updateWorkspace:
    post:
      consumes:
      - application/json
      operationId: updateWorkspace
      parameters:
      - description: UpdateWorkspaceBody
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateWorkspaceBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response-string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrResponse'
      summary: Update workspace
      tags:
      - workspace
schemes:
- http
swagger: "2.0"
